### ISSUE TITLE
Implement a Wordpress import tool

### ISSUE THREAD

**Issue by tgalopin** [openaction/openaction#54]
## Global aim

Implement an import User Interface in Citipo projects so that any user can upload a Wordpress export file to populate its website quickly.

A Wordpress export file can contain posts and pages but also other entities (feedbacks, ...). For now, we will only support posts, pages and attachments.

## General description of the feature

This system should work the same way that users can upload an Excel file containing contacts data to populate their database (you can see how it works in the section Organization > Import contacts):

1. In each project, a new menu item should be present in the sidebar, in the Configuration section, just above Projects settings. This item should be displayed only if the project has the website posts or the website pages enabled.
2. When clicking this menu item, the user should see  file upload input to send their Wordpress XML, similar to contacts import: ![image](https://github.com/openaction/openaction/assets/1651494/9627c820-1154-4cc8-802f-21794f78b384). They should have the ability to choose the import mode: either import all posts as draft, or import posts with the same status as in Wordpress. Only published pages should be imported as there is no draft system for pages on Citipo (thus no need for an option for pages).
3. Once uploaded, the users will see a progress bar for the import (see the way it works for contacts through a Messenger handler and the Job entity to track progress). At the end of the import, the user will see a success message.

## Architecture and references

* All displayed text need to use the translator as it will be translated in French, English and German. You can put the English translation in all languages for now (I'll translate in French and German).
* To see the code for the contacts import, see `App\Controller\Console\Organization\Community\ImportController`
* The upload system should use the already integrated Uploadcare platform
* The import controller should do as little work as possible: basically store the import configuration and dispatch a Messenger message to start the import
* All features should be tested using Symfony Web tests, and optionally Kernel/Unit tests can be added for specific classes where it's useful (for instance, the import Messenger handler here).
* During import, the `wp:post_type` XML tag can be used to differentiate entities: 
    * `page` items should be imported as Page entities in OpenAction
    * `post` items should be imported as Post entities in OpenAction
    * `attachment` items should only be imported when they are an image **and** their `wp:post_parent` tag relates to an imported page or post. In such cases, the attachment should be downloaded and set as the main picture of the imported page/post.

## Example Wordpress file

Here is an example of Wordpres export file that we should support:
[example-wordpress-export-file.xml.zip](https://github.com/openaction/openaction/files/14186044/example-wordpress-export-file.xml.zip)

Note it's been compressed in ZIP here as GitHub doesn't accept XML files but the tool should only accept XML files.

## Tasks

- [ ] Add the menu item in projects with the posts or pages module enabled
- [ ] Implement the form to receive uploaded Wordpress export files as well as the import mode for posts (all draft or keep Wordpress status)
- [ ] Implement the import Messenger handlers and job status update
- [ ] Implement the progress bar display
- [ ] Add tests for the upload form
- [ ] Add tests for all the Messenger handlers created
